name: Node.js Package
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*" #si considerano solo i tag del tipo v1.2.0
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@mind-informatica-srl'
      - name: Installazione npm
        run: npm install
      - name: Installazione angular 12.2.10
        run: npm i -g @angular/cli@12.2.10
      - name: Versionamento libreria
        run: cd projects/mind-angular-lib
      - run: npm version ${GITHUB_REF##*/}
      - run: cd ../../
      - name: Build libreria
        run: ng build mind-angular-lib
      - run: cd dist/mind-angular-lib  
      - name: Pubblicazione npm  
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          